#!/usr/bin/env python3
"""
First-Time Setup Wizard for Voice Command AI System
Run this once after installing dependencies
"""

import os
import sys
import json
import time
import subprocess
from pathlib import Path

class Colors:
    """ANSI color codes for terminal output"""
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_header(text):
    """Print a formatted header"""
    print(f"\n{Colors.HEADER}{'='*60}{Colors.END}")
    print(f"{Colors.HEADER}{text.center(60)}{Colors.END}")
    print(f"{Colors.HEADER}{'='*60}{Colors.END}\n")

def print_success(text):
    """Print success message"""
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")

def print_error(text):
    """Print error message"""
    print(f"{Colors.RED}✗ {text}{Colors.END}")

def print_info(text):
    """Print info message"""
    print(f"{Colors.CYAN}ℹ {text}{Colors.END}")

def print_warning(text):
    """Print warning message"""
    print(f"{Colors.YELLOW}⚠ {text}{Colors.END}")

def check_python_version():
    """Check if Python version is 3.8 or higher"""
    print_header("Checking Python Version")
    
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print_error(f"Python 3.8+ required. You have {version.major}.{version.minor}")
        return False
    
    print_success(f"Python {version.major}.{version.minor}.{version.micro} ✓")
    return True

def check_dependencies():
    """Check if all required packages are installed"""
    print_header("Checking Dependencies")
    
    required_packages = [
        'PyQt5',
        'speech_recognition',
        'selenium',
        'psutil',
        'google.generativeai',
        'groq',
        'requests',
        'flask',
        'dotenv'
    ]
    
    missing = []
    
    for package in required_packages:
        try:
            __import__(package.replace('.', '_').replace('-', '_'))
            print_success(f"{package}")
        except ImportError:
            print_error(f"{package} - NOT INSTALLED")
            missing.append(package)
    
    if missing:
        print_warning("\nMissing packages detected!")
        print_info("Please run: pip install -r requirements.txt")
        return False
    
    print_success("\nAll dependencies installed!")
    return True

def setup_api_keys():
    """Setup API keys in .env file"""
    print_header("API Keys Setup")
    
    print_info("You need at least ONE API key for the system to work.")
    print_info("Groq is recommended (fast & free): https://console.groq.com/keys\n")
    
    api_keys = {}
    
    providers = {
        'GROQ_API_KEY': ('Groq', 'https://console.groq.com/keys'),
        'GEMINI_API_KEY': ('Google Gemini', 'https://makersuite.google.com/app/apikey'),
        'DEEPSEEK_API_KEY': ('DeepSeek', 'https://platform.deepseek.com/api_keys'),
        'HUGGINGFACE_API_KEY': ('HuggingFace', 'https://huggingface.co/settings/tokens'),
        'COHERE_API_KEY': ('Cohere', 'https://dashboard.cohere.com/api-keys'),
        'MISTRAL_API_KEY': ('Mistral', 'https://console.mistral.ai/api-keys')
    }
    
    for key_name, (provider_name, url) in providers.items():
        print(f"\n{Colors.BOLD}{provider_name}{Colors.END}")
        print(f"Get your key from: {Colors.CYAN}{url}{Colors.END}")
        
        api_key = input(f"Enter your {provider_name} API key (or press Enter to skip): ").strip()
        
        if api_key:
            api_keys[key_name] = api_key
            print_success(f"{provider_name} API key saved!")
    
    if not api_keys:
        print_error("\nNo API keys provided!")
        print_info("You need at least one API key. Please restart setup.")
        return False
    
    # Write to .env file
    env_path = Path('.env')
    with open(env_path, 'w') as f:
        f.write("# Voice Command AI - API Keys\n")
        f.write("# Generated by setup wizard\n\n")
        for key, value in api_keys.items():
            f.write(f'{key}="{value}"\n')
    
    print_success(f"\n✓ API keys saved to .env file")
    print_info(f"  Total keys configured: {len(api_keys)}")
    
    return True

def setup_chrome_profile():
    """Setup Chrome profile for WhatsApp and Form Filler"""
    print_header("Chrome Profile Setup")
    
    print_info("Chrome profiles are needed for:")
    print_info("  1. WhatsApp Web automation")
    print_info("  2. Auto Form Filler")
    print_info("  3. ChatGPT automation\n")
    
    choice = input("Do you want to setup Chrome profiles now? (y/n): ").lower()
    
    if choice != 'y':
        print_warning("Skipping Chrome profile setup.")
        print_info("You can run main_setup.py later to configure this.")
        return True
    
    try:
        # Run the existing Chrome setup script
        print_info("\nRunning Chrome profile setup...")
        subprocess.run([sys.executable, 'main_setup.py'], check=True)
        print_success("Chrome profile setup complete!")
        return True
    except Exception as e:
        print_error(f"Chrome setup failed: {e}")
        print_info("You can run 'python main_setup.py' later to configure this.")
        return True

def setup_user_data():
    """Setup user data for form filler"""
    print_header("Form Filler - Personal Data Setup")
    
    print_info("The Auto Form Filler needs your personal information.")
    print_info("This data is stored locally and never shared.\n")
    
    choice = input("Do you want to setup your personal data now? (y/n): ").lower()
    
    if choice != 'y':
        print_warning("Skipping personal data setup.")
        print_info("You can edit Auto_Form_Filler/user_data.json later.")
        
        # Copy example file
        import shutil
        shutil.copy('Auto_Form_Filler/user_data.example.json', 
                   'Auto_Form_Filler/user_data.json')
        return True
    
    print("\n" + Colors.BOLD + "Enter your personal information:" + Colors.END)
    
    user_data = {
        "personal_info": {},
        "education": {},
        "professional": {},
        "learned_questions": {},
        "preferences": {
            "auto_fill_enabled": True,
            "confirmation_required": False,
            "learn_new_questions": True
        }
    }
    
    # Personal Info
    print(f"\n{Colors.CYAN}--- Personal Information ---{Colors.END}")
    user_data["personal_info"]["full_name"] = input("Full Name: ").strip()
    user_data["personal_info"]["first_name"] = input("First Name: ").strip()
    user_data["personal_info"]["last_name"] = input("Last Name: ").strip()
    user_data["personal_info"]["email"] = input("Email: ").strip()
    user_data["personal_info"]["phone"] = input("Phone: ").strip()
    user_data["personal_info"]["date_of_birth"] = input("Date of Birth (DD-MM-YYYY): ").strip()
    user_data["personal_info"]["gender"] = input("Gender (Male/Female/Other): ").strip()
    user_data["personal_info"]["address"] = input("Address: ").strip()
    user_data["personal_info"]["city"] = input("City: ").strip()
    user_data["personal_info"]["state"] = input("State: ").strip()
    user_data["personal_info"]["country"] = input("Country: ").strip()
    user_data["personal_info"]["zip_code"] = input("ZIP Code: ").strip()
    user_data["personal_info"]["nationality"] = input("Nationality: ").strip()
    
    # Education
    print(f"\n{Colors.CYAN}--- Education (Press Enter to skip) ---{Colors.END}")
    user_data["education"]["highest_degree"] = input("Highest Degree: ").strip()
    user_data["education"]["institution"] = input("Institution: ").strip()
    user_data["education"]["major"] = input("Major/Stream: ").strip()
    user_data["education"]["graduation_year"] = input("Graduation Year: ").strip()
    user_data["education"]["gpa"] = input("GPA/Percentage: ").strip()
    
    # Professional
    print(f"\n{Colors.CYAN}--- Professional (Press Enter to skip) ---{Colors.END}")
    user_data["professional"]["occupation"] = input("Occupation: ").strip()
    user_data["professional"]["company"] = input("Company: ").strip()
    user_data["professional"]["job_title"] = input("Job Title: ").strip()
    user_data["professional"]["years_of_experience"] = input("Years of Experience: ").strip()
    user_data["professional"]["industry"] = input("Industry: ").strip()
    
    # Save to file
    user_data_path = Path('Auto_Form_Filler/user_data.json')
    with open(user_data_path, 'w') as f:
        json.dump(user_data, f, indent=2)
    
    print_success("\n✓ Personal data saved to Auto_Form_Filler/user_data.json")
    return True

def create_whatsapp_config():
    """Create WhatsApp API config from .env"""
    print_header("WhatsApp Automation Setup")
    
    # Check if .env exists and has GROQ key
    env_path = Path('.env')
    if not env_path.exists():
        print_warning("No .env file found. Skipping WhatsApp config.")
        return True
    
    # Read GROQ key from .env
    groq_key = None
    with open(env_path, 'r') as f:
        for line in f:
            if line.startswith('GROQ_API_KEY'):
                groq_key = line.split('=')[1].strip().strip('"')
                break
    
    if groq_key and groq_key != "your-groq-api-key-here":
        config = {
            "api_keys": {
                "groq": groq_key
            },
            "api_priority": ["groq"],
            "timeout_seconds": 30
        }
        
        config_path = Path('Chat_Automation/whatsapp_api_config.json')
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
        
        print_success("✓ WhatsApp automation configured with your Groq API key")
    else:
        print_info("Groq API key not found. WhatsApp automation will use main config.")
    
    return True

def create_logs_directory():
    """Create logs directory structure"""
    print_header("Creating Directory Structure")
    
    directories = [
        'logs',
        'Chat_Automation/whatsapp_profile',
        'Chat_Automation/chatgpt_profile'
    ]
    
    for directory in directories:
        path = Path(directory)
        path.mkdir(parents=True, exist_ok=True)
        print_success(f"Created: {directory}")
    
    # Create .gitkeep files to preserve empty directories
    for directory in directories:
        gitkeep = Path(directory) / '.gitkeep'
        gitkeep.touch()
    
    return True

def create_setup_complete_flag():
    """Create a flag file to indicate setup is complete"""
    flag_file = Path('.setup_complete')
    with open(flag_file, 'w') as f:
        f.write(json.dumps({
            'setup_date': time.strftime('%Y-%m-%d %H:%M:%S'),
            'version': '1.0'
        }, indent=2))
    print_success("✓ Setup completion flag created")

def print_final_instructions():
    """Print final instructions and next steps"""
    print_header("Setup Complete!")
    
    print(f"{Colors.GREEN}{Colors.BOLD}✓ All setup steps completed successfully!{Colors.END}\n")
    
    print(f"{Colors.CYAN}Next Steps:{Colors.END}")
    print(f"1. Run the application:")
    print(f"   {Colors.BOLD}python run.py{Colors.END}")
    print(f"   or")
    print(f"   {Colors.BOLD}python main.py{Colors.END}\n")
    
    print(f"2. Click the microphone button to start listening\n")
    
    print(f"3. Try these example commands:")
    print(f"   • 'search for python tutorials'")
    print(f"   • 'take screenshot'")
    print(f"   • 'show my productivity'")
    print(f"   • 'open chrome'\n")
    
    print(f"{Colors.YELLOW}Important Notes:{Colors.END}")
    print(f"• Your API keys are in .env (keep this file secure)")
    print(f"• Your personal data is in Auto_Form_Filler/user_data.json")
    print(f"• All configuration files are ignored by git")
    print(f"• Check README.md for full command list\n")
    
    print(f"{Colors.CYAN}Need Help?{Colors.END}")
    print(f"• Read USER_GUIDE.md for detailed usage instructions")
    print(f"• Check TROUBLESHOOTING.md if you face issues")
    print(f"• Review logs/ directory for error messages\n")

def main():
    """Main setup function"""
    print_header("Voice Command AI - First-Time Setup Wizard")
    
    print(f"{Colors.CYAN}This wizard will help you configure:{Colors.END}")
    print("  1. API Keys for AI providers")
    print("  2. Chrome profiles for automation")
    print("  3. Personal data for form filling")
    print("  4. Directory structure")
    print("")
    
    input("Press Enter to continue...")
    
    # Step 1: Check Python version
    if not check_python_version():
        sys.exit(1)
    
    time.sleep(1)
    
    # Step 2: Check dependencies
    if not check_dependencies():
        print_error("\nSetup cannot continue without dependencies.")
        print_info("Run: pip install -r requirements.txt")
        sys.exit(1)
    
    time.sleep(1)
    
    # Step 3: Setup API keys
    if not setup_api_keys():
        sys.exit(1)
    
    time.sleep(1)
    
    # Step 4: Create directory structure
    create_logs_directory()
    time.sleep(1)
    
    # Step 5: Setup Chrome profiles
    setup_chrome_profile()
    time.sleep(1)
    
    # Step 6: Setup user data
    setup_user_data()
    time.sleep(1)
    
    # Step 7: Create WhatsApp config
    create_whatsapp_config()
    time.sleep(1)
    
    # Step 8: Create setup complete flag
    create_setup_complete_flag()
    
    # Step 9: Print final instructions
    print_final_instructions()
    
    print(f"\n{Colors.GREEN}{Colors.BOLD}{'='*60}{Colors.END}")
    print(f"{Colors.GREEN}{Colors.BOLD}Setup completed successfully! 🎉{Colors.END}")
    print(f"{Colors.GREEN}{Colors.BOLD}{'='*60}{Colors.END}\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print_error("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print_error(f"\n\nSetup failed with error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)